# Generated by Django 2.2.4 on 2019-08-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('name', models.TextField(max_length=100)),
                ('year_published', models.IntegerField(blank=True, default=None, null=True)),
                ('min_players', models.IntegerField(blank=True, default=None, null=True)),
                ('max_players', models.IntegerField(blank=True, default=None, null=True)),
                ('playing_time', models.IntegerField(blank=True, default=None, null=True)),
                ('min_play_time', models.IntegerField(blank=True, default=None, null=True)),
                ('max_play_time', models.IntegerField(blank=True, default=None, null=True)),
                ('min_age', models.IntegerField(blank=True, default=None, null=True)),
                ('num_ratings', models.IntegerField(blank=True, default=None, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('bayes_average_rating', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, default=None, null=True)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgdb.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='RankingList',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=60)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('boardgames', models.ManyToManyField(through='bgdb.Placement', to='bgdb.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('boardgames', models.ManyToManyField(to='bgdb.Boardgame')),
            ],
        ),
        migrations.AddField(
            model_name='placement',
            name='ranking_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgdb.RankingList'),
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('boardgames', models.ManyToManyField(to='bgdb.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('boardgames', models.ManyToManyField(to='bgdb.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('boardgames', models.ManyToManyField(to='bgdb.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('boardgames', models.ManyToManyField(to='bgdb.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('boardgames', models.ManyToManyField(to='bgdb.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='AlternateName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgdb.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedPlayerPollResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_count', models.IntegerField(blank=True, default=None, null=True)),
                ('highest_count', models.BooleanField(default=False)),
                ('response', models.CharField(choices=[('NR', 'Not Recommended'), ('RC', 'Recommneded'), ('BE', 'Best')], max_length=2)),
                ('num_votes', models.IntegerField(blank=True, default=None, null=True)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgdb.Boardgame')),
            ],
            options={
                'unique_together': {('player_count', 'response', 'boardgame')},
            },
        ),
        migrations.CreateModel(
            name='SuggestedAgePollResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('highest_age', models.BooleanField(default=False)),
                ('num_votes', models.IntegerField(blank=True, default=None, null=True)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgdb.Boardgame')),
            ],
            options={
                'unique_together': {('age', 'boardgame')},
            },
        ),
        migrations.CreateModel(
            name='LanguageDependencyPollResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_level', models.IntegerField(blank=True, default=None, null=True)),
                ('dependency_text', models.CharField(max_length=30)),
                ('num_votes', models.IntegerField(blank=True, default=None, null=True)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgdb.Boardgame')),
            ],
            options={
                'unique_together': {('dependency_level', 'boardgame')},
            },
        ),
    ]
