# Generated by Django 2.2.4 on 2019-08-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagedependencypollresponse',
            name='dependency_text',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='suggestedplayerpollresponse',
            name='response',
            field=models.CharField(choices=[('NR', 'Not Recommended'), ('RC', 'Recommended'), ('BE', 'Best')], max_length=2),
        ),
    ]
