# Generated by Django 2.2.4 on 2019-08-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgdb', '0002_auto_20190817_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatename',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.TextField(max_length=150),
        ),
    ]
