# Generated by Django 2.2.4 on 2019-08-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgdb', '0003_auto_20190817_1655'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placement',
            unique_together={('boardgame', 'ranking_list')},
        ),
    ]
