# Generated by Django 2.2.4 on 2019-08-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgdb', '0004_auto_20190819_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatename',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
