# Generated by Django 2.2.4 on 2019-08-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgdb', '0005_auto_20190819_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
