# Generated by Django 2.2.4 on 2019-08-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgdb', '0006_auto_20190819_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatename',
            name='name',
            field=models.TextField(),
        ),
    ]
