# Generated by Django 2.2.4 on 2019-08-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgdb', '0007_auto_20190819_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
