# Generated by Django 2.2.4 on 2019-08-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgdb', '0009_auto_20190819_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='designer',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='rankinglist',
            name='display_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='rankinglist',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
